### ISSUE TITLE
Translate: [Directory Structure]

### ISSUE THREAD

**Issue by masebb** [hugojapan/ja#21]
### 翻訳元英語ドキュメントへのリンク

- [Directory Structure | Hugo](https://gohugo.io/getting-started/directory-structure/)

### 作業ファイル

- [ja/getting-started/directory-structure.md ](https://github.com/hugojapan/ja/blob/71d139f07d4edcf82215b0b5ee62ddec26a233eb/getting-started/directory-structure.md)

**Comment by masebb** [comment]
翻訳します。

**Comment by peaceiris** [comment]
Twitter からの話の続きですが
`git submodule add` がうまくできませんか?

もともとある `content/ja` を消してもらう必要があるかもしれません。

```
git rm content/ja
git submodule add https://github.com/[your_github_id]/ja.git content/ja
```

**Comment by mira-gfx** [comment]
出来ない
```
masetaiyounoMacBook-Pro:ja mira_gfx$ git submodule add -f https://github.com/mira-gfx/ja.git content/ja
Cloning into '/Users/mira_gfx/Hugo-doc-jp/hugoDocs/content/ja/content/ja'...
remote: Repository not found.
fatal: repository 'https://github.com/mira-gfx/ja.git/' not found
fatal: clone of 'https://github.com/mira-gfx/ja.git' into submodule path '/Users/mira_gfx/Hugo-doc-jp/hugoDocs/content/ja/content/ja' failed
```

**Comment by masebb** [comment]
やってみます
(Closeしてすみません)

**Comment by peaceiris** [comment]
Reopen します?

最悪、ローカルで `hugo server` しなくてもいいなら、単純にこのリポジトリで PR を出せば Netlify deploy preview でサイトの確認ができます。

こんな感じで👉 https://github.com/hugojapan/ja/pull/20#issuecomment-473517759

**Comment by masebb** [comment]
Reopenしちゃってください

**Comment by peaceiris** [comment]
たしかにもともと submodule があるので、削除しないとダメですね。説明不足でした、すみません。

作業内容、修正しました👇
https://github.com/hugojapan/hugojapan.github.io/commit/0014a518cf591221752e030a25386d028938f78c

**Comment by masebb** [comment]
```git rm content/ja```
したら行けました。ご丁寧な対応ありがとうございます☺️
