### ISSUE TITLE
Translate: Sitemap Template

### ISSUE THREAD

**Issue by tosi29** [hugojapan/ja#24]
### 翻訳元英語ドキュメントへのリンク

- [Sitemap Template](https://gohugo.io/templates/sitemap-template/)

### 作業ファイル

- [ja/sitemap-template.md at master](https://github.com/hugojapan/ja/blob/master/templates/sitemap-template.md)

**Comment by tosi29** [comment]
翻訳します

**Comment by peaceiris** [comment]
よろしくお願いします。
